spring.application.name=TeacherManagement

server.port=8080

#database 
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDb1
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#datajpa/hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format-sql=true
spring.jpa.show-sql=true
spring.jpa.datasource-platform=org.hibernate.dialect.OracleDialect
